spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    jdbc-url: jdbc:postgresql://${postgres_host:localhost}:5432/${postgres_database:slave1}
#    username: ${postgres_username:postgres}
#    password: ${postgres_password:admin}
